#!/usr/bin/env bash
podman run -d \
  --name nginx-server \
  --replace \
  -v ./default.conf:/etc/nginx/conf.d/default.conf \
  -v ./html:/usr/share/nginx/html/ \
  -p 8080:80 docker.io/library/nginx:latest
